import os
import sys
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, KeepTogether, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch

def build_pdf():
    pdf_filename = r"c:\JavaTrainingFSE\Week-5 Angular\HandsOn1_Report.pdf"
    doc = SimpleDocTemplate(pdf_filename, pagesize=letter,
                            rightMargin=54, leftMargin=54,
                            topMargin=54, bottomMargin=54)

    styles = getSampleStyleSheet()
    
    # Custom Styles for Premium Look
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=24,
        leading=28,
        textColor=colors.HexColor('#1e293b'),
        spaceAfter=15,
        alignment=1 # Center
    )
    
    subtitle_style = ParagraphStyle(
        'DocSub',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor('#4f46e5'),
        spaceAfter=30,
        alignment=1
    )
    
    h1_style = ParagraphStyle(
        'SectionH1',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=15,
        leading=18,
        textColor=colors.HexColor('#1e293b'),
        spaceBefore=18,
        spaceAfter=8,
        borderPadding=4
    )

    h2_style = ParagraphStyle(
        'SectionH2',
        parent=styles['Heading3'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=15,
        textColor=colors.HexColor('#4f46e5'),
        spaceBefore=10,
        spaceAfter=4
    )

    body_style = ParagraphStyle(
        'DocBody',
        parent=styles['BodyText'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=13.5,
        textColor=colors.HexColor('#334155'),
        spaceAfter=6
    )

    code_style = ParagraphStyle(
        'CodeStyle',
        parent=styles['Normal'],
        fontName='Courier',
        fontSize=7.5,
        leading=10,
        textColor=colors.HexColor('#0f172a'),
        backColor=colors.HexColor('#f8fafc'),
        borderColor=colors.HexColor('#cbd5e1'),
        borderWidth=0.5,
        borderPadding=6,
        spaceBefore=4,
        spaceAfter=4
    )

    meta_style = ParagraphStyle(
        'MetaStyle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=13.5,
        textColor=colors.HexColor('#475569')
    )

    story = []

    # --- COVER PAGE & GENERAL HEADER ---
    story.append(Spacer(1, 40))
    story.append(Paragraph("DIGITAL NURTURE 5.0", subtitle_style))
    story.append(Paragraph("Angular (v20+) Hands-On Lab Report", title_style))
    story.append(Paragraph("Incremental Project: Student Course Portal", subtitle_style))
    story.append(Spacer(1, 20))
    
    # Metadata Table
    meta_data = [
        [Paragraph("<b>Hands-On:</b>", meta_style), Paragraph("Hands-On 1 [Beginner]", meta_style)],
        [Paragraph("<b>Topic:</b>", meta_style), Paragraph("Environment Setup, Project Structure & First Component", meta_style)],
        [Paragraph("<b>Developer:</b>", meta_style), Paragraph("Cathy George", meta_style)],
        [Paragraph("<b>OS Version:</b>", meta_style), Paragraph("Windows 11", meta_style)],
        [Paragraph("<b>Date:</b>", meta_style), Paragraph("July 22, 2026", meta_style)],
        [Paragraph("<b>Track:</b>", meta_style), Paragraph("Java FSE Angular Track", meta_style)]
    ]
    t_meta = Table(meta_data, colWidths=[2.0 * inch, 4.5 * inch])
    t_meta.setStyle(TableStyle([
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
        ('BACKGROUND', (0,0), (0,-1), colors.HexColor('#f1f5f9')),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('PADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(t_meta)
    story.append(Spacer(1, 40))
    story.append(PageBreak())

    # --- SECTION 2: OBJECTIVE ---
    story.append(Paragraph("1. Objective", h1_style))
    obj_text = ("The primary objective of this hands-on exercise is to establish a modern Angular development environment "
                "using the Angular CLI, scaffold the Student Course Portal project structure, explore the role and purpose "
                "of crucial configuration files generated by the CLI, and build the foundation pages including the header "
                "navigation bar and the initial welcome dashboard.")
    story.append(Paragraph(obj_text, body_style))
    story.append(Spacer(1, 10))

    # --- SECTION 3: ANGULAR CONCEPTS COVERED ---
    story.append(Paragraph("2. Angular Concepts Covered", h1_style))
    concepts = [
        "<b>Angular CLI (Command Line Interface):</b> Used for scaffolding, building, generating code components, and running local dev servers.",
        "<b>Project Structure & Bootstrapping:</b> Understanding how main.ts bootstraps the root application config and component in modern standalone mode.",
        "<b>Standalone Components:</b> Creating components using the newer standalone pattern (default in v17/18/19/20/21) which bypasses the legacy NgModule structure.",
        "<b>Single Page Application (SPA) Routing:</b> Configuring path-component mappings in routes to load pages dynamically inside the router-outlet.",
        "<b>Component Styling & Encapsulation:</b> Organizing modular styles (scoped to header, home, etc.) alongside global style overrides in styles.css."
    ]
    for c in concepts:
        story.append(Paragraph(f"• {c}", body_style))
    story.append(Spacer(1, 10))

    # --- SECTION 4: SOFTWARE USED ---
    story.append(Paragraph("3. Software & Tools Used", h1_style))
    sw_data = [
        [Paragraph("<b>Software / Tool</b>", meta_style), Paragraph("<b>Version / URL</b>", meta_style)],
        [Paragraph("Node.js + npm", meta_style), Paragraph("v22.20.0 (LTS 20+) / npm 10.9.3", meta_style)],
        [Paragraph("Angular CLI", meta_style), Paragraph("v21.2.16", meta_style)],
        [Paragraph("Code Editor", meta_style), Paragraph("VS Code with Angular Language Service Extension", meta_style)],
        [Paragraph("Web Browser", meta_style), Paragraph("Google Chrome + DevTools", meta_style)],
        [Paragraph("PDF Generator", meta_style), Paragraph("Python 3.14 + ReportLab library", meta_style)]
    ]
    t_sw = Table(sw_data, colWidths=[2.5 * inch, 4.0 * inch])
    t_sw.setStyle(TableStyle([
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#e2e8f0')),
        ('PADDING', (0,0), (-1,-1), 5),
    ]))
    story.append(t_sw)
    story.append(Spacer(1, 10))

    # --- SECTION 5: COMMANDS EXECUTED ---
    story.append(Paragraph("4. Commands Executed", h1_style))
    cmd_data = [
        [Paragraph("<b>Step / Action</b>", meta_style), Paragraph("<b>Command Line</b>", meta_style)],
        [Paragraph("Scaffold New Project", meta_style), Paragraph("<code>ng new student-course-portal --routing --style=css --ssr=false</code>", meta_style)],
        [Paragraph("Navigate to directory", meta_style), Paragraph("<code>cd student-course-portal</code>", meta_style)],
        [Paragraph("Generate Header component", meta_style), Paragraph("<code>ng generate component components/header</code>", meta_style)],
        [Paragraph("Generate Home component", meta_style), Paragraph("<code>ng generate component pages/home</code>", meta_style)],
        [Paragraph("Generate Course List component", meta_style), Paragraph("<code>ng generate component pages/course-list</code>", meta_style)],
        [Paragraph("Generate Student Profile component", meta_style), Paragraph("<code>ng generate component pages/student-profile</code>", meta_style)],
        [Paragraph("Run Application Locally", meta_style), Paragraph("<code>ng serve</code>", meta_style)],
        [Paragraph("Build Production Bundle", meta_style), Paragraph("<code>ng build</code>", meta_style)]
    ]
    t_cmd = Table(cmd_data, colWidths=[2.2 * inch, 4.3 * inch])
    t_cmd.setStyle(TableStyle([
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#f8fafc')),
        ('PADDING', (0,0), (-1,-1), 4),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    story.append(t_cmd)
    story.append(Spacer(1, 10))

    # --- SECTION 6: FOLDER STRUCTURE ---
    story.append(Paragraph("5. Project Folder Structure", h1_style))
    folder_text = ("student-course-portal/<br/>"
                   "├── angular.json (CLI settings)<br/>"
                   "├── package.json (dependencies)<br/>"
                   "├── tsconfig.json (TS config)<br/>"
                   "├── notes.txt (exercise documentation)<br/>"
                   "└── src/<br/>"
                   "    ├── index.html (main layout entry)<br/>"
                   "    ├── main.ts (bootstrap entry)<br/>"
                   "    ├── styles.css (global style variables)<br/>"
                   "    └── app/<br/>"
                   "        ├── app.config.ts (providers & routing imports)<br/>"
                   "        ├── app.routes.ts (route mappings)<br/>"
                   "        ├── app.ts (root component logic)<br/>"
                   "        ├── app.html (header + router-outlet wrapper)<br/>"
                   "        ├── components/<br/>"
                   "        │   └── header/ (Header navbar component)<br/>"
                   "        └── pages/<br/>"
                   "            ├── home/ (Dashboard component)<br/>"
                   "            ├── course-list/ (Course offering details placeholder)<br/>"
                   "            └── student-profile/ (Student info placeholder)")
    story.append(Paragraph(folder_text, code_style))
    story.append(Spacer(1, 10))
    story.append(PageBreak())

    # --- SECTION 7: CODE IMPLEMENTATION ---
    story.append(Paragraph("6. Code Implementation Details", h1_style))
    
    # app.routes.ts
    story.append(Paragraph("Root Routing Configuration (src/app/app.routes.ts)", h2_style))
    routes_code = ("import { Routes } from '@angular/router';<br/>"
                   "import { Home } from './pages/home/home';<br/>"
                   "import { CourseList } from './pages/course-list/course-list';<br/>"
                   "import { StudentProfile } from './pages/student-profile/student-profile';<br/><br/>"
                   "export const routes: Routes = [<br/>"
                   "  { path: '', component: Home },<br/>"
                   "  { path: 'courses', component: CourseList },<br/>"
                   "  { path: 'profile', component: StudentProfile },<br/>"
                   "  { path: '**', redirectTo: '' }<br/>"
                   "];")
    story.append(Paragraph(routes_code, code_style))
    
    # app.ts
    story.append(Paragraph("Root Component Class (src/app/app.ts)", h2_style))
    app_ts_code = ("import { Component, signal } from '@angular/core';<br/>"
                   "import { RouterOutlet } from '@angular/router';<br/>"
                   "import { Header } from './components/header/header';<br/><br/>"
                   "@Component({<br/>"
                   "  selector: 'app-root',<br/>"
                   "  imports: [RouterOutlet, Header],<br/>"
                   "  templateUrl: './app.html',<br/>"
                   "  styleUrl: './app.css'<br/>"
                   "})<br/>"
                   "export class App {<br/>"
                   "  protected readonly title = signal('student-course-portal');<br/>"
                   "}")
    story.append(Paragraph(app_ts_code, code_style))
    
    # header.ts
    story.append(Paragraph("Header Navigation Class (src/app/components/header/header.ts)", h2_style))
    header_ts_code = ("import { Component } from '@angular/core';<br/>"
                      "import { RouterLink, RouterLinkActive } from '@angular/router';<br/><br/>"
                      "@Component({<br/>"
                      "  selector: 'app-header',<br/>"
                      "  imports: [RouterLink, RouterLinkActive],<br/>"
                      "  templateUrl: './header.html',<br/>"
                      "  styleUrl: './header.css',<br/>"
                      "})<br/>"
                      "export class Header {}")
    story.append(Paragraph(header_ts_code, code_style))
    story.append(PageBreak())

    # --- SECTION 8: SCREENSHOTS & OUTPUT ---
    story.append(Paragraph("7. Captured Screenshots & Verification", h1_style))
    story.append(Paragraph("Visual rendering of the portal layout verified on Chrome browser:", body_style))

    # Add Screenshots if files exist
    img_paths = [
        (r"C:\Users\User\.gemini\antigravity-ide\brain\effa0dc0-f48f-4fcb-bba2-671db0428b78\home_page_1784709605674.png", "Home Dashboard with hardcoded stats (Courses: 12, Enrolled: 3, GPA: 3.8)"),
        (r"C:\Users\User\.gemini\antigravity-ide\brain\effa0dc0-f48f-4fcb-bba2-671db0428b78\courses_page_1784709667097.png", "Course Offerings list placeholder page loaded via routing"),
        (r"C:\Users\User\.gemini\antigravity-ide\brain\effa0dc0-f48f-4fcb-bba2-671db0428b78\profile_page_1784709700069.png", "Student Profile placeholder page loaded via routing")
    ]
    
    for path, caption in img_paths:
        if os.path.exists(path):
            try:
                # Resize image flowable for PDF fit (keeping aspect ratio)
                # Original: ~800x600, let's fit inside 4.5inch width
                img = Image(path, width=4.5*inch, height=3.0*inch)
                story.append(Paragraph(f"<b>Screenshot:</b> {caption}", h2_style))
                story.append(img)
                story.append(Spacer(1, 8))
            except Exception as e:
                story.append(Paragraph(f"[Image Render Error: {str(e)}]", body_style))
        else:
            story.append(Paragraph(f"<b>[Screenshot Placeholder]:</b> {caption} (Screenshot file not found at path)", body_style))

    story.append(Spacer(1, 10))
    story.append(PageBreak())

    # --- SECTION 9: OUTPUT EXPLANATION ---
    story.append(Paragraph("8. Output Explanation", h1_style))
    out_text = ("• <b>Home Page:</b> Features a dark cyber-slate aesthetic. The header nav remains fixed at the top with a glassmorphism blur. "
                "The welcome panel highlights cumulative statistics inside styled gradient cards. Sub-pages are reachable directly via links.<br/>"
                "• <b>Routing:</b> When clicking 'Courses' or 'Profile', the router intercepts the navigation, updates the active link styles "
                "with an animated glowing underscore, and renders the placeholder components instantly without reloading the browser window.<br/>"
                "• <b>Production Build:</b> Running <code>npm run build</code> outputs a production bundle inside <code>dist/student-course-portal/browser/</code> "
                "containing <code>index.html</code>, a single compressed JS bundle (<code>main-*.js</code>), and a compiled style sheet (<code>styles-*.css</code>). "
                "The budget limit checks were triggered and verified successfully.")
    story.append(Paragraph(out_text, body_style))
    story.append(Spacer(1, 10))

    # --- SECTION 10: CHALLENGES FACED ---
    story.append(Paragraph("9. Challenges Faced & Troubleshooting", h1_style))
    challenges = [
        "<b>PowerShell Security Policies:</b> Windows execution policies blocked running <code>ng</code> scripts. <i>Fix:</i> Invoked Angular CLI tasks by wrapping with <code>npx</code> or overriding execution policies locally.",
        "<b>Angular Standalone Module Structure:</b> The default project scaffolding uses Standalone components (no <code>app.module.ts</code>). <i>Fix:</i> Resolved compiler issues by manually importing routing directives (<code>RouterLink</code>, <code>RouterLinkActive</code>) in the Standalone Component imports rather than rely on global declarations.",
        "<b>CSS Layout Responsiveness:</b> Maintaining a clean layout for the stats section on mobile viewports. <i>Fix:</i> Used a CSS Grid layout with auto-fit parameters (<code>repeat(auto-fit, minmax(280px, 1fr))</code>) to ensure clean responsive wrapping."
    ]
    for ch in challenges:
        story.append(Paragraph(ch, body_style))
    story.append(Spacer(1, 10))

    # --- SECTION 11: LEARNING OUTCOMES ---
    story.append(Paragraph("10. Learning Outcomes", h1_style))
    learnings = [
        "Understood the initialization and directory setup of Angular workspaces.",
        "Discovered how modern Angular standalone components are declared and imported.",
        "Successfully set up client-side routing using dynamic routing states.",
        "Created custom typography and glassmorphic aesthetic interfaces using CSS variables.",
        "Inspected bundle structures generated during production compilation."
    ]
    for l in learnings:
        story.append(Paragraph(f"✓ {l}", body_style))
    story.append(Spacer(1, 10))

    # --- SECTION 12: CONCLUSION ---
    story.append(Paragraph("11. Conclusion", h1_style))
    concl_text = ("Hands-On 1 successfully establishes a clean, modern, and highly modular starting point for the Student Course "
                  "Portal. Leveraging the standalone design API and structured routing patterns, the scaffold is ready to "
                  "support the feature implementations planned for future exercises.")
    story.append(Paragraph(concl_text, body_style))

    # Build PDF Document
    doc.build(story)
    print("PDF Report compiled successfully at:", pdf_filename)

if __name__ == '__main__':
    build_pdf()
